utils::globalVariables(c("ABH", "CD_STAT",  "IDD", "VAX", "X",  "Y",
                         "code_espece", "code_station", "date_peche", "effectif", "localisation",
                         "organisme", "type_peche", "Date", "x_wgs84", "y_wgs84", "Ctxte_Pech",
                         "esp_code_sandre", "esp_nom_latin", "lop_effectif", "lop_id", "ope_date",
                         "pop_code_sandre", "pop_coordonnees_x", "pop_coordonnees_y", "proj_pop",
                         "protocole_peche", "sta_code_sandre",
                         "Bassin", "code_exutoire", "esp_code_alternatif", "point_prelevement", "pop_id",
                         "pop_libelle", "pro_libelle", "sta_id", "typ_code_epsg", "utilisateur", "x_l93", "y_l93",
                         "CdStationMesureEauxSurface", "CoordXPointEauxSurf", "CoordYPointEauxSurf",
                         "L1_Li_Nom", "NomEntiteHydrographique", "Op_Dtd", "VAR", "annee",
                         "Date_peche", "source_donnee",
                         ".", "Cours d'eau", "Espèce", "Type", "Nb Individus"))
